version: '3'
services:

  db-esic-online:
    container_name: db-esic-online
    image: postgis/postgis:13-master
    restart: always
    volumes:
      - ./data/db-esic-online:/var/lib/postgresql/data
    networks:
      - applications-network
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db-esic-online'

  cache-esic-online:
    container_name: cache-esic-online
    restart: always
    image: redis:6
    networks:
      - applications-network
  adminer-4.8.1:
    image: adminer:4.8.1
    container_name: adminer-4.8.1
    restart: always
    depends_on:
      - cache-esic-online
      - db-esic-online
    ports:
      - 8082:8080
    networks:
      - applications-network
  admin-esic-online:
    container_name: admin-esic-online
    image: directus/directus:9.21.0
    restart: always
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./db-esic-online:/directus/db-esic-online
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - applications-network
    depends_on:
      - cache-esic-online
      - db-esic-online
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'db-esic-online'
      DB_PORT: '5432'
      DB_DATABASE: 'db-esic-online'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache-esic-online:6379'

      ADMIN_EMAIL: 'admin@esic-online.com'
      ADMIN_PASSWORD: '7hCO&JwalTuJtDnblgIu95oY%xO'


      EMAIL_FROM: 'admin@esic-online.com'
      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: 'mails.dev'
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

volumes:
  esic-online:
  esic-online-config:
  esic-online-src:

networks:
  applications-network:
