version: '3.8'
services:
  esic-online-database:
    container_name: esic-online-database
    image: postgis/postgis:13-master
    restart: always
    volumes:
      - ./data/esic-online-database:/var/lib/postgresql/data
    networks:
      - applications-network
    environment:
      POSTGRES_USER: PROD_DATABASE_USERNAME
      POSTGRES_PASSWORD: PROD_DATABASE_PASSWORD
      POSTGRES_DB: 'esic-online-database'
  esic-online-database-ihm:
    container_name: esic-online-database-ihm
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8057:8080
    networks:
      - applications-network
  esic-online-cache:
    container_name: esic-online-cache
    restart: always
    image: redis:6
    networks:
      - applications-network
  esic-online-backoffice:
    container_name: esic-online-backoffice
    image: directus/directus:9.21.0
    restart: always
    ports:
      - 8056:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - esic-online-backoffice-uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./esic-online-database:/directus/esic-online-database
      # If you want to load extensions from the host
      - esic-online-backoffice-extensions:/directus/extensions
    networks:
      - applications-network
    depends_on:
      - esic-online-cache
      - esic-online-database
    environment:
      LOG_LEVEL: 'info'
      CORS_ORIGIN: 'true'
      CORS_ENABLED: 'true'
      PUBLIC_URL: 'https://build.esic-online.chillo.fr'
      KEY: PROD_ADMINISTRATION_TOKEN
      SECRET: PROD_ADMINISTRATION_SECRET
      DB_CLIENT: 'pg'
      DB_HOST: 'esic-online-database'
      DB_PORT: '5432'
      DB_DATABASE: 'esic-online-database'
      DB_USER: PROD_DATABASE_USERNAME
      DB_PASSWORD: PROD_DATABASE_PASSWORD

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://esic-online-cache:6379'

      ADMIN_EMAIL: PROD_ADMINISTRATION_USERNAME
      ADMIN_PASSWORD: PROD_ADMINISTRATION_PASSWORD

      EMAIL_FROM: PROD_ADMINISTRATION_USERNAME
      EMAIL_TRANSPORT: smtp
      #EMAIL_SMTP_HOST: smtp-relay.sendinblue.com
      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587

      #EMAIL_SMTP_PASSWORD: dqm1hzycTgOnCQ2s
      #EMAIL_SMTP_USER: accueil@chillo.tech
      EMAIL_SMTP_PASSWORD: PROD_SMTP_PASSWORD
      EMAIL_SMTP_USER: PROD_SMTP_USERNAME
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

volumes:
  esic-online-backoffice:
  esic-online-backoffice-config:
  esic-online-backoffice-src:
  esic-online-backoffice-uploads:
  esic-online-backoffice-extensions:
networks:
  applications-network:
    external: true
